;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.023

name=App-FzfUtils

[Prereqs]
perl=5.010001
strict=0
warnings=0
File::Trash::FreeDesktop=0.207
File::Which=0
Image::Size=0
IPC::System::Options=0.339
Log::ger=0.038
Perinci::Exporter=0.080
Perinci::Object=0.311
Process::Status=0
Regexp::Pattern::Filename::Image::WhatsApp=0

[Prereqs / DevelopX_spec]
-phase=develop
-relationship=x_spec
Rinci=1.1.102
